import { useCallback, useEffect, useRef, useState } from "react";
import { check, type Update } from "@tauri-apps/plugin-updater";
import { relaunch } from "@tauri-apps/plugin-process";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { commands } from "../bindings";
import { showToast } from "../toast";

/** How often to re-test window visibility while the launch check is deferred.
 *  Only ever runs on an autostart launch, and stops the moment the window is
 *  revealed. */
const VISIBILITY_POLL_MS = 4000;

/** Matches the grace period `quit_app` allows on the tray-quit path: long
 *  enough for the frontend's history flush and the meta writer to land before
 *  the installer terminates the process. */
const SHUTDOWN_GRACE_MS = 1200;

/** What the update flow is currently doing.
 *
 *  `downloading` is deliberately silent — no dialog, no toast. The user finds
 *  out when it's `ready` and there's something they can actually act on;
 *  telling them mid-download only offers a wait. */
export type UpdateStage = "idle" | "checking" | "downloading" | "ready" | "installing";

export type UpdateState = {
  stage: UpdateStage;
  /** Set from `downloading` onward. Null in every other stage. */
  version: string | null;
  /** 0-100 while downloading, -1 when the server sent no content length. */
  percent: number;
  /** The feed marked this release `critical` (see `readCritical`). Such an
   *  update is not left sitting behind a link the user can ignore. */
  critical: boolean;
};

const IDLE: UpdateState = { stage: "idle", version: null, percent: 0, critical: false };

/** `latest.json` is generated by tauri-action, which emits no such field — it
 *  is added by hand to the draft release before publishing, for the rare fix
 *  that can't wait for people to get around to restarting. The updater plugin
 *  passes the whole parsed feed through as `rawJson`, so no custom endpoint is
 *  needed to read it.
 *
 *  Anything other than a literal `true` is treated as not critical: this comes
 *  off the network, and the failure that matters is a malformed feed silently
 *  escalating every ordinary update into a forced restart. */
function readCritical(update: Update): boolean {
  return update.rawJson?.critical === true;
}

/** `onRequestInstall` fires when the user accepts the ready-toast. It asks for
 *  the restart rather than performing it: restarting interrupts whatever is
 *  downloading, so the decision belongs behind a confirmation the caller owns
 *  (it's the one that knows how many downloads are in flight). */
export function useUpdateCheck(
  onRequestInstall: () => void,
  opts: {
    /** Settings' "Install updates at startup". Ignored for a critical update. */
    autoInstall: boolean;
    /** Downloads active or queued right now. Auto-install stands down when
     *  anything is in flight, so it never interrupts work the user started. */
    inFlight: number;
  },
) {
  const [state, setState] = useState<UpdateState>(IDLE);

  // The `Update` handle owns the downloaded package; it has to survive from the
  // silent download all the way to whenever the user finally clicks install,
  // which may be days later. A ref rather than state because nothing renders
  // from it directly.
  const updateRef = useRef<Update | null>(null);

  // Declared up front so the callbacks below can reach the latest values
  // without taking each other as dependencies.
  const requestInstallRef = useRef(onRequestInstall);
  requestInstallRef.current = onRequestInstall;
  const stageRef = useRef<UpdateStage>("idle");
  stageRef.current = state.stage;
  // Read at the moment the download finishes, not when it started — by then
  // the user may well have queued something.
  const optsRef = useRef(opts);
  optsRef.current = opts;
  const installRef = useRef<() => void>(() => {});

  /** Downloads in the background, then decides how loudly to surface it —
   *  see the branch at the end. */
  const downloadSilently = useCallback(async (update: Update) => {
    updateRef.current = update;
    const critical = readCritical(update);
    setState({ stage: "downloading", version: update.version, percent: 0, critical });

    let total = 0;
    let received = 0;
    try {
      await update.download((ev) => {
        if (ev.event === "Started") {
          total = ev.data.contentLength ?? 0;
        } else if (ev.event === "Progress") {
          received += ev.data.chunkLength;
          const pct = total > 0 ? Math.min(100, Math.round((received / total) * 100)) : -1;
          setState((s) => ({ ...s, percent: pct }));
        }
      });
    } catch {
      // Silent by design: this download was never user-initiated, so a failed
      // one shouldn't produce an error the user didn't ask for. The next
      // launch, or a manual check, tries again.
      updateRef.current = null;
      setState(IDLE);
      return;
    }

    setState({ stage: "ready", version: update.version, percent: 100, critical });

    // A critical update is never left behind a link the user can ignore. It
    // still goes through the prompt rather than restarting underneath them —
    // the dialog just won't take no for an answer (see `critical` in
    // UpdateRestartDialog).
    if (critical) {
      requestInstallRef.current();
      return;
    }

    // Startup is the cheapest moment to restart: the user hasn't started
    // anything yet. Checking `inFlight` now rather than when the download
    // began, because it takes a while and they may have queued something
    // since. Anything in flight falls through to the patient path below.
    if (optsRef.current.autoInstall && optsRef.current.inFlight === 0) {
      showToast(`Installing version ${update.version}…`, "info");
      installRef.current();
      return;
    }

    showToast(`Version ${update.version} is ready to install.`, "info", {
      label: "Restart now",
      // Opens the confirmation rather than installing outright — this toast
      // can be clicked while a download is mid-flight. Read off the ref
      // because the toast outlives the render that created it.
      onClick: () => requestInstallRef.current(),
    });
  }, []);

  /** `silent` is the launch check: no update simply means no UI. The manual
   *  check reports every outcome, including "you're up to date", because a
   *  button that looks like it did nothing is worse than a boring answer. */
  const runCheck = useCallback(
    async (silent: boolean) => {
      // Already downloaded and waiting — re-checking would discard a finished
      // download to start the same one over.
      if (updateRef.current && stageRef.current === "ready") {
        if (!silent) showToast("An update is already downloaded and ready.", "info");
        return;
      }

      setState({ ...IDLE, stage: "checking" });
      let update: Update | null;
      try {
        update = await check();
      } catch (e) {
        setState(IDLE);
        // Offline at launch is the common case and not worth interrupting for.
        if (!silent) showToast(`Couldn't check for updates: ${e}`, "error");
        return;
      }

      if (!update) {
        updateRef.current = null;
        setState(IDLE);
        if (!silent) showToast("You're on the latest version.", "info");
        return;
      }

      if (!silent) showToast(`Downloading version ${update.version} in the background…`, "info");
      downloadSilently(update);
    },
    [downloadSilently],
  );

  const checkNow = useCallback(() => runCheck(false), [runCheck]);

  const install = useCallback(async () => {
    const update = updateRef.current;
    if (!update) return;
    setState((s) => ({ ...s, stage: "installing" }));

    // The installer terminates this process, bypassing the tray-quit path
    // entirely — so run that path's preparation by hand first: pause in-flight
    // downloads so their resume sidecars are written, and let the frontend
    // flush history instead of losing whatever was still inside its debounce.
    try {
      await commands.prepareForUpdate();
      await new Promise((r) => setTimeout(r, SHUTDOWN_GRACE_MS));
    } catch {
      // Preparation is best-effort; failing it is not a reason to strand the
      // user on a stale build with an update already downloaded.
    }

    try {
      await update.install();
    } catch (e) {
      setState((s) => ({ ...s, stage: "ready", percent: 100 }));
      showToast(`Update failed to install: ${e}`, "error");
      return;
    }

    // On Windows the installer usually takes the app down itself, so this is
    // often never reached. It exists for the case where it doesn't.
    try {
      await relaunch();
    } catch {
      showToast("Update installed — restart to finish.", "info");
    }
  }, []);

  installRef.current = install;

  // One silent check per launch. Deliberately not on an interval: this app can
  // sit open for days, and re-checking on a timer would mean discarding or
  // duplicating an already-downloaded update for no benefit.
  //
  // Held until the window is actually on screen. An autostart launch
  // (`--autostart`) deliberately stays hidden in the tray, and the ready-toast
  // would otherwise fire into a window nobody can see. Forcing the window open
  // would override the very setting the user chose, so this waits for them.
  const didLaunchCheck = useRef(false);
  useEffect(() => {
    if (didLaunchCheck.current) return;
    didLaunchCheck.current = true;

    let cancelled = false;
    let timer: ReturnType<typeof setInterval> | undefined;

    // `isVisible` failing is treated as visible: a missed update is a worse
    // outcome than one surfaced while the window happens to be hidden, and
    // this is the ordinary (non-autostart) path.
    async function checkIfVisible(): Promise<boolean> {
      const visible = await getCurrentWindow()
        .isVisible()
        .catch(() => true);
      if (cancelled || !visible) return false;
      runCheck(true);
      return true;
    }

    checkIfVisible().then((done) => {
      if (done || cancelled) return;
      timer = setInterval(() => {
        checkIfVisible().then((ok) => {
          if (ok && timer) clearInterval(timer);
        });
      }, VISIBILITY_POLL_MS);
    });

    return () => {
      cancelled = true;
      if (timer) clearInterval(timer);
    };
  }, [runCheck]);

  return { state, checkNow, install };
}
