// ---------------------------------------------------------------------------
// Pending update — silent install.
//
// The updater plugin's own `install()` always runs the NSIS installer with
// `/R` (relaunch) and, in its default Passive mode, a visible progress
// window — there is no way to make that call truly silent from the JS side.
// So the download happens here instead: `download_update` fetches and
// signature-verifies the update package (the plugin's `Update::download`
// already does the verification) and writes it to disk, recording it in a
// small `pending-update.json` file of its own — kept separate from
// `AppSettings` for the same reason `config/prefs.rs` is (see its module
// comment): `save_settings` overwrites the whole settings object from the
// frontend's own state, which would silently erase a pending-update record
// written from here.
//
// Installing later means spawning that saved installer ourselves with NSIS's
// silent flags, choosing `/R` (relaunch) or not depending on whether the app
// is supposed to come back afterward.
// ---------------------------------------------------------------------------

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, Manager as _};
use tauri_plugin_updater::UpdaterExt;

use crate::config::settings::SettingsState;
use crate::config::{config_dir, write_json_atomic};

#[derive(Serialize, Deserialize, Clone, Default, specta::Type)]
#[serde(rename_all = "camelCase", default)]
pub(crate) struct PendingUpdate {
    /// Version string exactly as the feed reported it.
    pub(crate) version: String,
    /// Absolute path of the downloaded NSIS installer.
    pub(crate) installer: String,
    /// The feed marked this release `critical`; persisted so a pending
    /// update picked up at the next launch still forces the restart dialog.
    pub(crate) critical: bool,
}

#[derive(Serialize, Clone, specta::Type)]
#[serde(rename_all = "camelCase")]
pub(crate) struct UpdateInfo {
    pub(crate) version: String,
    pub(crate) critical: bool,
}

fn pending_path() -> Result<PathBuf, String> {
    Ok(config_dir()?.join("pending-update.json"))
}

fn pending_dir() -> Result<PathBuf, String> {
    Ok(config_dir()?.join("pending-update"))
}

/// `None` on any error — a missing file is the normal case (nothing pending)
/// and not worth surfacing.
fn read_pending() -> Option<PendingUpdate> {
    let bytes = std::fs::read(pending_path().ok()?).ok()?;
    serde_json::from_slice(&bytes).ok()
}

/// Best-effort, and only removes the metadata file. The installer `.exe`
/// itself is left in place until the next `download_update` recreates the
/// whole directory — nothing depends on it being gone a moment sooner.
fn clear_pending() {
    if let Ok(path) = pending_path() {
        let _ = std::fs::remove_file(path);
    }
}

/// A stored pending update, but only if it's still actually installable: its
/// installer file exists and it isn't for the version already running (e.g.
/// this process *is* that update, having just relaunched after installing
/// it). Clears a stale record so every caller doesn't have to.
fn valid_pending(app: &AppHandle) -> Option<PendingUpdate> {
    let pending = read_pending()?;
    let current_version = app.package_info().version.to_string();
    if pending.version == current_version || !Path::new(&pending.installer).is_file() {
        clear_pending();
        return None;
    }
    Some(pending)
}

/// Checks the feed, downloads and signature-verifies the update package (the
/// plugin's own `download` does the verification), and records it as
/// pending. `Ok(None)` when already up to date.
#[tauri::command]
#[specta::specta]
pub(crate) async fn download_update(app: AppHandle) -> Result<Option<UpdateInfo>, String> {
    let updater = app.updater().map_err(|e| e.to_string())?;
    let Some(update) = updater.check().await.map_err(|e| e.to_string())? else {
        return Ok(None);
    };

    // `latest.json` is generated by tauri-action, which emits no such field
    // — it's added by hand to the draft release before publishing, for the
    // rare fix that can't wait for people to get around to restarting.
    // Anything other than a literal `true` is treated as not critical: this
    // comes off the network, and the failure that matters is a malformed
    // feed silently escalating every ordinary update into a forced restart.
    let critical = update.raw_json.get("critical") == Some(&serde_json::Value::Bool(true));
    let version = update.version.clone();

    // Lets the frontend show its "downloading" stage before the (possibly
    // slow) download below finishes.
    let _ = app.emit_to(
        "main",
        "update-downloading",
        UpdateInfo { version: version.clone(), critical },
    );

    let bytes = update.download(|_, _| {}, || {}).await.map_err(|e| e.to_string())?;

    // The only artifact this app ever ships an update as (see the module
    // comment) — reject anything else outright rather than write out
    // something a later silent spawn would run unchecked.
    if bytes.len() < 2 || &bytes[..2] != b"MZ" {
        return Err("Update artifact is not a Windows installer".to_string());
    }

    // Recreated from scratch so installers from earlier checks/versions
    // don't accumulate.
    let dir = pending_dir()?;
    let _ = tokio::fs::remove_dir_all(&dir).await;
    tokio::fs::create_dir_all(&dir).await.map_err(|e| e.to_string())?;
    let installer = dir.join(format!("{version}-setup.exe"));
    tokio::fs::write(&installer, &bytes).await.map_err(|e| e.to_string())?;

    let pending = PendingUpdate {
        version: version.clone(),
        installer: installer.to_string_lossy().into_owned(),
        critical,
    };
    write_json_atomic(&pending_path()?, &pending).await?;

    Ok(Some(UpdateInfo { version, critical }))
}

/// What the frontend shows at launch without re-downloading — e.g. the
/// status bar's "Restart to update" button.
#[tauri::command]
#[specta::specta]
pub(crate) fn pending_update(app: AppHandle) -> Option<UpdateInfo> {
    valid_pending(&app).map(|p| UpdateInfo { version: p.version, critical: p.critical })
}

/// Explicit "Restart now" path: install and relaunch. Callers must run
/// `prepare_for_update` (pause downloads, flush history) and wait out its
/// grace period first — this only handles the installer itself.
#[tauri::command]
#[specta::specta]
pub(crate) fn install_pending_update(app: AppHandle) -> Result<(), String> {
    let pending = valid_pending(&app).ok_or_else(|| "No update is ready to install".to_string())?;
    // Cleared before spawning: a failed install must never turn into a boot
    // loop on the next launch — worst case is one wasted re-download.
    clear_pending();
    spawn_installer(Path::new(&pending.installer), true)?;
    std::process::exit(0);
}

/// `relaunch` adds NSIS's `/R` so the installer starts the app again when it
/// finishes. Left off on the quit path: the user asked for the app to be
/// gone, and an update must not bring it back.
///
/// `/ARGS` with nothing after it is exactly what the updater plugin itself
/// emits when the process had no argv of its own, so the installer script
/// already handles the empty case.
#[cfg(windows)]
fn spawn_installer(installer: &Path, relaunch: bool) -> Result<(), String> {
    use std::os::windows::process::CommandExt;
    const CREATE_NO_WINDOW: u32 = 0x0800_0000;
    const DETACHED_PROCESS: u32 = 0x0000_0008;

    let mut cmd = std::process::Command::new(installer);
    cmd.arg("/S").arg("/UPDATE");
    if relaunch {
        cmd.arg("/R").arg("/ARGS");
    }
    cmd.creation_flags(CREATE_NO_WINDOW | DETACHED_PROCESS);
    cmd.spawn().map_err(|e| e.to_string())?;
    Ok(())
}

#[cfg(not(windows))]
fn spawn_installer(_installer: &Path, _relaunch: bool) -> Result<(), String> {
    Err("Silent update install is only implemented on Windows".to_string())
}

/// Called from `quit_app` after the shutdown grace period. Installs a
/// pending update without `/R`, so the app really does stay closed. Honors
/// the `autoInstallUpdates` setting; a `critical` update isn't special-cased
/// here because it already forced the restart dialog when it arrived.
pub(crate) fn try_install_on_quit(app: &AppHandle) {
    if !app.state::<SettingsState>().0.lock().unwrap().auto_install_updates {
        return;
    }
    let Some(pending) = valid_pending(app) else { return };
    clear_pending();
    let _ = spawn_installer(Path::new(&pending.installer), false);
}

/// Called first thing in `setup()`, before any window exists — so a pending
/// update left over from a force-kill or a reboot installs before anything
/// is visible, rather than surfacing mid-session. Returns true if an
/// installer was launched, in which case the caller must exit immediately:
/// the rest of startup would just be torn down moments later anyway, and the
/// relaunching installer brings up a fresh, fully-started process instead.
pub(crate) fn try_install_on_cold_start(app: &AppHandle) -> bool {
    if !app.state::<SettingsState>().0.lock().unwrap().auto_install_updates {
        return false;
    }
    let Some(pending) = valid_pending(app) else { return false };
    clear_pending();
    spawn_installer(Path::new(&pending.installer), true).is_ok()
}
