// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startDownload: (args: StartDownloadArgs, onEvent: Channel<DownloadEvent>) => __TAURI_INVOKE<null>("start_download", { args, onEvent }),
	pauseDownload: (id: string) => __TAURI_INVOKE<void>("pause_download", { id }),
	cancelDownload: (id: string) => __TAURI_INVOKE<void>("cancel_download", { id }),
	/**
	 *  Set the global download speed cap in bytes/sec (0 = unlimited). Live —
	 *  affects all active downloads immediately since they share this bucket.
	 */
	setGlobalSpeedLimit: (args: SpeedLimitArgs) => __TAURI_INVOKE<void>("set_global_speed_limit", { args }),
	/**
	 *  Set one download's own speed cap in bytes/sec (0 = unlimited). Live — the
	 *  running workers share this bucket, so it takes effect on the next chunk.
	 */
	setDownloadSpeedLimit: (id: string, args: SpeedLimitArgs) => __TAURI_INVOKE<void>("set_download_speed_limit", { id, args }),
	/**
	 *  Remove a row's resume sidecar (always) and, if requested, the file itself.
	 *  Save folders are now user-chosen, so this only sanity-checks the path
	 *  instead of confining it to the default downloads/temp roots.
	 */
	deleteDownload: (path: string, deleteFile: boolean) => __TAURI_INVOKE<null>("delete_download", { path, deleteFile }),
	listResumable: () => __TAURI_INVOKE<ResumableInfo[]>("list_resumable"),
	/**
	 *  Re-checks whether each path still exists, in the same order as `paths` —
	 *  used by the frontend to refresh a finished row's "missing" status on
	 *  demand (window refocus, F5, the toolbar Refresh button) instead of only
	 *  once at `load_history` time.
	 */
	checkPathsMissing: (paths: string[]) => __TAURI_INVOKE<boolean[]>("check_paths_missing", { paths }),
	/**
	 *  Check a URL's size and filename ahead of committing to a download, for the
	 *  Add window's live "Size:" readout. Reuses the same client/probe path as an
	 *  actual download so the reported size matches what a real run would see.
	 */
	probeUrl: (url: string, allowInsecure: boolean, headers: ([string, string])[], proxy: {
	enabled?: boolean,
	/**  "http" | "https" | "socks5h" */
	scheme?: string,
	host?: string,
	port?: number,
	username?: string,
	password?: string,
} | null) => __TAURI_INVOKE<ProbeInfo>("probe_url", { url, allowInsecure, headers, proxy }),
	/**  The default destination folder, for the Add window's "Save path" field. */
	defaultDownloadDir: () => __TAURI_INVOKE<string>("default_download_dir"),
	/**
	 *  Folder containing the unpacked browser extension, for the titlebar
	 *  "install extension" button. In a bundled build this is the `extension`
	 *  resource shipped next to the app (see `bundle.resources` in
	 *  `tauri.conf.json`); in dev it's the `extension/` folder at the repo root.
	 *  `flavor` picks the build: "chrome" (Chromium/Edge/Brave) or "firefox"
	 *  (Firefox/Zen/LibreWolf), which ship as separate folders because Chrome and
	 *  Gecko disagree on the MV3 background key.
	 */
	extensionDir: (flavor: string | null) => __TAURI_INVOKE<string>("extension_dir", { flavor }),
	/**
	 *  Reveal the Add window for the "+" button case, and let it know it was
	 *  just opened so it can check the clipboard for a URL to prefill.
	 */
	openAddWindow: () => __TAURI_INVOKE<void>("open_add_window"),
	/**
	 *  Reveal the Add window without the clipboard-prefill side effect above —
	 *  used once the Add window has already been prefilled from a captured
	 *  download (extension deep link) and just needs to become visible.
	 */
	revealAddWindowCmd: () => __TAURI_INVOKE<void>("reveal_add_window_cmd"),
	closeAddWindow: () => __TAURI_INVOKE<void>("close_add_window"),
	/**
	 *  Build (or reveal, if it already exists) a "Download Details" popup for one
	 *  download, labeled `detail-<id>` — every row gets its own window instead of
	 *  all of them fighting over a single reused one. Unlike the Add window,
	 *  `main` is never disabled: these are non-modal inspectors the user can
	 *  leave open while continuing to work in the main table.
	 * 
	 *  The window is built hidden; `main`'s `detail-ready` handshake (once the
	 *  popup's own React tree has mounted and asked for its first snapshot) is
	 *  what actually shows it via `show_detail_window`, so there's never a flash
	 *  of an empty popup.
	 * 
	 *  Must be `async`: a plain (blocking) command runs inline on the same thread
	 *  that pumps WebView2's IPC messages — i.e. the main/UI thread. Creating a
	 *  *new* OS window needs to hand off to that same thread's event loop and
	 *  wait for it, which can't happen while that thread is busy running us, so
	 *  a non-async version of this command deadlocks the whole app the moment it
	 *  tries to build the window. Being `async` moves execution onto a tokio
	 *  worker thread first, so the handoff to the real UI thread can complete.
	 */
	openDetailWindow: (id: string) => __TAURI_INVOKE<null>("open_detail_window", { id }),
	/**
	 *  Show + focus a detail popup once its frontend has actually rendered the
	 *  snapshot `main` handed it (see `detail-ready` in `App.tsx`).
	 */
	showDetailWindow: (id: string) => __TAURI_INVOKE<void>("show_detail_window", { id }),
	/**
	 *  Destroy one detail popup (they're created on demand now, not pooled) and
	 *  tell `main` it's gone so it stops pushing snapshots at it.
	 * 
	 *  `async` for the same reason as `open_detail_window`: tearing down an OS
	 *  window is thread-affine like creating one, so this can't safely run
	 *  inline on the IPC/UI thread either.
	 */
	closeDetailWindow: (id: string) => __TAURI_INVOKE<void>("close_detail_window", { id }),
	/**
	 *  Push a fresh snapshot of active downloads into the tray menu, called
	 *  roughly once a second from the frontend. Patches labels in place when the
	 *  same set of ids is still showing (by far the common case) so the menu
	 *  doesn't visibly flicker; otherwise rebuilds it.
	 */
	updateTrayDownloads: (items: TrayDownload[], tooltip: string) => __TAURI_INVOKE<null>("update_tray_downloads", { items, tooltip }),
	loadSettings: () => __TAURI_INVOKE<AppSettings>("load_settings"),
	saveSettings: (settings: AppSettings) => __TAURI_INVOKE<null>("save_settings", { settings }),
	loadPrefs: () => __TAURI_INVOKE<Prefs>("load_prefs"),
	saveAddDefaults: (args: SaveAddDefaultsArgs) => __TAURI_INVOKE<null>("save_add_defaults", { args }),
	setCategoryPath: (category: string, path: string) => __TAURI_INVOKE<null>("set_category_path", { category, path }),
	loadHistory: () => __TAURI_INVOKE<HistoryLoad_Serialize>("load_history"),
	saveHistory: (entries: HistoryEntry_Deserialize[]) => __TAURI_INVOKE<null>("save_history", { entries }),
};

/* Types */
export type AppSettings = {
	maxConcurrent?: number,
	globalLimitMbps?: number | null,
	minimizeToTray?: boolean,
	/**
	 *  "system" | "dark" | "light". Applied entirely on the frontend (see
	 *  `src/theme.ts`); Rust only persists it.
	 */
	theme?: string,
	notifications?: boolean,
};

export type ConnInfo = {
	downloaded: number,
	total: number,
	pieces: number,
};

export type DownloadEvent = { event: "started"; data: {
	filename: string,
	path: string,
	total: number | null,
	connections: number,
	pieceSize: number,
	numPieces: number,
} } | { event: "progress"; data: {
	downloaded: number,
	total: number | null,
	speedBps: number | null,
	connections: ConnInfo[],
} } | { event: "paused"; data: {
	downloaded: number,
} } | { event: "canceled"; data: {
	downloaded: number,
} } | { event: "verifying" } | { event: "finished"; data: {
	path: string,
	filename: string,
} } | { event: "error"; data: {
	message: string,
} };

/**
 *  One finished download. `state` always holds the real terminal state —
 *  "missing" is never stored, it is recomputed from disk on every load so a
 *  file that reappears recovers its original status.
 */
export type HistoryEntry = HistoryEntry_Serialize | HistoryEntry_Deserialize;

/**
 *  One finished download. `state` always holds the real terminal state —
 *  "missing" is never stored, it is recomputed from disk on every load so a
 *  file that reappears recovers its original status.
 */
export type HistoryEntry_Deserialize = {
	id?: string,
	url?: string,
	/**  Credential headers are stripped before this is written — see `needs_auth`. */
	headers?: ([string, string])[],
	allowInsecure?: boolean,
	checksum?: string,
	speedLimit?: number,
	filename?: string,
	filenameOverride?: string,
	path?: string,
	savePath?: string,
	total?: number | null,
	downloaded?: number,
	connections?: number,
	usedConnections?: number,
	state?: string,
	error?: string | null,
	/**
	 *  Kept so a redownload of a credential-gated link can reopen the page
	 *  that produced it and wait for the extension to capture a fresh request.
	 */
	referer?: string,
	needsAuth?: boolean,
	proxy?: ProxyConfig,
	finishedAt?: number,
	/**
	 *  When this download first entered the list; 0 for rows persisted before
	 *  this field existed (the frontend falls back to `finished_at` then).
	 */
	addedAt?: number,
};

/**
 *  One finished download. `state` always holds the real terminal state —
 *  "missing" is never stored, it is recomputed from disk on every load so a
 *  file that reappears recovers its original status.
 */
export type HistoryEntry_Serialize = {
	id: string,
	url: string,
	/**  Credential headers are stripped before this is written — see `needs_auth`. */
	headers: ([string, string])[],
	allowInsecure: boolean,
	checksum: string,
	speedLimit: number,
	filename: string,
	filenameOverride: string,
	path: string,
	savePath: string,
	total: number | null,
	downloaded: number,
	connections: number,
	usedConnections: number,
	state: string,
	error: string | null,
	/**
	 *  Kept so a redownload of a credential-gated link can reopen the page
	 *  that produced it and wait for the extension to capture a fresh request.
	 */
	referer: string,
	needsAuth: boolean,
	proxy: ProxyConfig,
	finishedAt: number,
	/**
	 *  When this download first entered the list; 0 for rows persisted before
	 *  this field existed (the frontend falls back to `finished_at` then).
	 */
	addedAt: number,
	missing: boolean,
};

export type HistoryLoad = HistoryLoad_Serialize | HistoryLoad_Deserialize;

export type HistoryLoad_Deserialize = {
	entries: HistoryEntry_Deserialize[],
	/**
	 *  False only when an existing file could not be parsed. The frontend uses
	 *  this to refuse to save for the rest of the session, so one bad byte
	 *  can't cascade into overwriting everything that was still readable.
	 */
	readable: boolean,
};

export type HistoryLoad_Serialize = {
	entries: HistoryEntry_Serialize[],
	/**
	 *  False only when an existing file could not be parsed. The frontend uses
	 *  this to refuse to save for the rest of the session, so one bad byte
	 *  can't cascade into overwriting everything that was still readable.
	 */
	readable: boolean,
};

export type Prefs = {
	/**  Add-window defaults, remembered across sessions. */
	connections?: number,
	speedLimitMbps?: number | null,
	/**
	 *  category id ("video" | "audio" | …) → absolute folder override.
	 *  Absent or empty = the built-in `<base>/<Category>` folder.
	 */
	categoryPaths?: { [key in string]: string },
	proxy?: ProxyConfig,
};

export type ProbeInfo = {
	total: number | null,
	supportsRanges: boolean,
	filename: string,
};

export type ProxyConfig = {
	enabled?: boolean,
	/**  "http" | "https" | "socks5h" */
	scheme?: string,
	host?: string,
	port?: number,
	username?: string,
	password?: string,
};

export type ResumableInfo = {
	path: string,
	url: string,
	filename: string,
	total: number,
	connections: number,
	downloaded: number,
	savePath: string | null,
	addedAt: number | null,
};

/**
 *  `save_add_defaults`'s own arguments, bundled into one struct so
 *  `connections` (a bare `usize`) can carry the `#[specta(type = Number)]`
 *  override needed to export it as `number` rather than `bigint` — that
 *  attribute is only available on `#[derive(Type)]` struct fields, not on
 *  raw `#[specta::specta]` command parameters. See `StartDownloadArgs` in
 *  `commands.rs` for the same pattern.
 */
export type SaveAddDefaultsArgs = {
	connections: number,
	speedLimitMbps: number | null,
	proxy: ProxyConfig,
};

/**
 *  A bare `u64`/`usize` command parameter can't carry the
 *  `#[specta(type = Number)]` override needed to export it as `number`
 *  rather than `bigint` — that attribute only works on `#[derive(Type)]`
 *  struct fields (see `StartDownloadArgs` above). Shared by the two
 *  speed-limit commands below, both of which take just this one value.
 */
export type SpeedLimitArgs = {
	bytesPerSec: number,
};

/**
 *  `start_download`'s own arguments, bundled into one struct rather than left
 *  as separate parameters: specta's `#[specta::specta]` macro (used to
 *  generate `../src/bindings.ts`) only implements its `SpectaFn` trait for
 *  functions of up to 10 parameters, and this command's domain arguments
 *  alone numbered 12. Grouping them costs nothing at the call site — Tauri's
 *  `invoke()` already sends named args as a single JSON object either way.
 */
export type StartDownloadArgs = {
	id: string,
	url: string,
	allowInsecure: boolean,
	headers: ([string, string])[],
	connections: number,
	resume: boolean,
	resumePath: string | null,
	expectedChecksum: string | null,
	speedLimit: number | null,
	filename: string | null,
	savePath: string | null,
	proxy: ProxyConfig | null,
};

export type TrayDownload = {
	id: string,
	label: string,
};

