// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startDownload: (args: StartDownloadArgs, onEvent: Channel<DownloadEvent>) => __TAURI_INVOKE<null>("start_download", { args, onEvent }),
	pauseDownload: (id: string) => __TAURI_INVOKE<void>("pause_download", { id }),
	cancelDownload: (id: string) => __TAURI_INVOKE<void>("cancel_download", { id }),
	/**
	 *  Set the global download speed cap in bytes/sec (0 = unlimited). Live —
	 *  affects all active downloads immediately since they share this bucket.
	 */
	setGlobalSpeedLimit: (args: SpeedLimitArgs) => __TAURI_INVOKE<void>("set_global_speed_limit", { args }),
	/**
	 *  Set one download's own speed cap in bytes/sec (0 = unlimited). Live — the
	 *  running workers share this bucket, so it takes effect on the next chunk.
	 */
	setDownloadSpeedLimit: (id: string, args: SpeedLimitArgs) => __TAURI_INVOKE<void>("set_download_speed_limit", { id, args }),
	/**
	 *  Remove a row's resume sidecar (always) and, if requested, the file itself.
	 *  Save folders are now user-chosen, so this only sanity-checks the path
	 *  instead of confining it to the default downloads/temp roots.
	 */
	deleteDownload: (path: string, deleteFile: boolean) => __TAURI_INVOKE<null>("delete_download", { path, deleteFile }),
	listResumable: () => __TAURI_INVOKE<ResumableInfo[]>("list_resumable"),
	/**
	 *  Re-checks whether each path still exists, in the same order as `paths` —
	 *  used by the frontend to refresh a finished row's "missing" status on
	 *  demand (window refocus, F5, the toolbar Refresh button) instead of only
	 *  once at `load_history` time.
	 */
	checkPathsMissing: (paths: string[]) => __TAURI_INVOKE<boolean[]>("check_paths_missing", { paths }),
	/**
	 *  Check a URL's size and filename ahead of committing to a download, for the
	 *  Add window's live "Size:" readout. Reuses the same client/probe path as an
	 *  actual download so the reported size matches what a real run would see.
	 */
	probeUrl: (url: string, allowInsecure: boolean, headers: ([string, string])[], proxy: {
	enabled?: boolean,
	/**  "http" | "https" | "socks5h" */
	scheme?: string,
	host?: string,
	port?: number,
	username?: string,
	password?: string,
} | null) => __TAURI_INVOKE<ProbeInfo>("probe_url", { url, allowInsecure, headers, proxy }),
	/**
	 *  Check a remote archive's contents ahead of committing to the download,
	 *  for the Add window's "Preview contents" button. Reuses the same
	 *  probe/client path as `probe_url` and a real download, so a listing here
	 *  reflects exactly what downloading the file would get.
	 */
	inspectArchive: (req: ArchiveRequest) => __TAURI_INVOKE<ArchiveListing>("inspect_archive", { req }),
	/**  The default destination folder, for the Add window's "Save path" field. */
	defaultDownloadDir: () => __TAURI_INVOKE<string>("default_download_dir"),
	/**
	 *  Soft pre-check for the Add window once the probe knows the size — the
	 *  engine re-checks (and hard-fails) at start regardless.
	 */
	checkDiskSpace: (savePath: string, filename: string, total: number | null) => __TAURI_INVOKE<DiskCheck>("check_disk_space", { savePath, filename, total }),
	/**
	 *  Folder containing the unpacked browser extension, for the titlebar
	 *  "install extension" button. In a bundled build this is the `extension`
	 *  resource shipped next to the app (see `bundle.resources` in
	 *  `tauri.conf.json`); in dev it's the `extension/` folder at the repo root.
	 *  `flavor` picks the build: "chrome" (Chromium/Edge/Brave) or "firefox"
	 *  (Firefox/Zen/LibreWolf), which ship as separate folders because Chrome and
	 *  Gecko disagree on the MV3 background key.
	 */
	extensionDir: (flavor: string | null) => __TAURI_INVOKE<string>("extension_dir", { flavor }),
	shellIcon: (ext: string) => __TAURI_INVOKE<string | null>("shell_icon", { ext }),
	/**
	 *  Reveal the Add window for the "+" button case, and let it know it was
	 *  just opened so it can check the clipboard for a URL to prefill.
	 */
	openAddWindow: () => __TAURI_INVOKE<void>("open_add_window"),
	/**
	 *  Reveal the Add window without the clipboard-prefill side effect above —
	 *  used once the Add window has already been prefilled from a captured
	 *  download (extension deep link) and just needs to become visible.
	 */
	revealAddWindowCmd: () => __TAURI_INVOKE<void>("reveal_add_window_cmd"),
	closeAddWindow: () => __TAURI_INVOKE<void>("close_add_window"),
	/**
	 *  Build (or reveal, if it already exists) a "Download Details" popup for one
	 *  download, labeled `detail-<id>` — every row gets its own window instead of
	 *  all of them fighting over a single reused one. Unlike the Add window,
	 *  `main` is never disabled: these are non-modal inspectors the user can
	 *  leave open while continuing to work in the main table.
	 * 
	 *  The window is built hidden; `main`'s `detail-ready` handshake (once the
	 *  popup's own React tree has mounted and asked for its first snapshot) is
	 *  what actually shows it via `show_detail_window`, so there's never a flash
	 *  of an empty popup.
	 * 
	 *  Must be `async`: a plain (blocking) command runs inline on the same thread
	 *  that pumps WebView2's IPC messages — i.e. the main/UI thread. Creating a
	 *  *new* OS window needs to hand off to that same thread's event loop and
	 *  wait for it, which can't happen while that thread is busy running us, so
	 *  a non-async version of this command deadlocks the whole app the moment it
	 *  tries to build the window. Being `async` moves execution onto a tokio
	 *  worker thread first, so the handoff to the real UI thread can complete.
	 */
	openDetailWindow: (id: string) => __TAURI_INVOKE<null>("open_detail_window", { id }),
	/**
	 *  Show + focus a detail popup once its frontend has actually rendered the
	 *  snapshot `main` handed it (see `detail-ready` in `App.tsx`).
	 */
	showDetailWindow: (id: string) => __TAURI_INVOKE<void>("show_detail_window", { id }),
	/**
	 *  Destroy one detail popup (they're created on demand now, not pooled) and
	 *  tell `main` it's gone so it stops pushing snapshots at it.
	 * 
	 *  `async` for the same reason as `open_detail_window`: tearing down an OS
	 *  window is thread-affine like creating one, so this can't safely run
	 *  inline on the IPC/UI thread either.
	 */
	closeDetailWindow: (id: string) => __TAURI_INVOKE<void>("close_detail_window", { id }),
	/**
	 *  Build (or, if one is already open, reveal and refresh) the "Preview
	 *  archive" popup for `req`, labeled `archive-preview` — a single window,
	 *  unlike the per-download `detail-<id>` popups, since only one preview is
	 *  ever relevant at a time. Owned by the Add window (not `main`) so it
	 *  floats above the modal Add dialog it was opened from, and is destroyed
	 *  (not hidden-and-reused) when closed — see `close_archive_window`.
	 * 
	 *  Built hidden: the frontend calls `show_archive_window` itself once it has
	 *  taken the stashed request and has at least a "Scanning…" state to show,
	 *  so there's never a flash of an empty popup. When reusing an
	 *  already-open window instead, there's no such gap to avoid — it's shown
	 *  immediately, and `archive-window-opened` tells its already-mounted React
	 *  tree to collect the new request and re-scan.
	 * 
	 *  Must be `async`: a plain (blocking) command runs inline on the same
	 *  thread that pumps WebView2's IPC messages — i.e. the main/UI thread.
	 *  Creating a *new* OS window needs to hand off to that same thread's event
	 *  loop and wait for it, which can't happen while that thread is busy
	 *  running us, so a non-async version of this command deadlocks the whole
	 *  app the moment it tries to build the window.
	 */
	openArchiveWindow: (req: ArchiveRequest) => __TAURI_INVOKE<null>("open_archive_window", { req }),
	/**
	 *  Show + focus the preview popup once its own React tree has taken the
	 *  stashed request and has something to display.
	 */
	showArchiveWindow: () => __TAURI_INVOKE<void>("show_archive_window"),
	takeArchiveRequest: () => __TAURI_INVOKE<{
	url: string,
	allowInsecure: boolean,
	headers: ([string, string])[],
	proxy: ProxyConfig | null,
} | null>("take_archive_request"),
	/**
	 *  Destroys the preview popup — created on demand, not pooled like the Add
	 *  window, so there's nothing to hide-and-reuse here; the next "Preview
	 *  contents" click just builds a fresh one.
	 * 
	 *  `async` for the same reason as `open_archive_window`: tearing down an OS
	 *  window is thread-affine like creating one.
	 */
	closeArchiveWindow: () => __TAURI_INVOKE<void>("close_archive_window"),
	/**
	 *  Build (or, if one is already open, reveal and focus) the "About" popup —
	 *  a single window, labeled `about`, triggered by clicking the app name in
	 *  `main`'s status bar. Owned by `main` (not modal — `main` stays usable
	 *  while it's open, like the per-download detail popups).
	 * 
	 *  Unlike the Archive Preview window, there's no async data to wait on —
	 *  everything shown (version, license, repo link) is either static or a
	 *  near-instant local read — so this builds straight to `.visible(true)`
	 *  rather than the build-hidden/`show_*`-once-ready handshake `archive.rs`
	 *  uses to avoid a flash of empty content while a real network scan runs.
	 * 
	 *  Must be `async`: a plain (blocking) command runs inline on the same
	 *  thread that pumps WebView2's IPC messages, and creating a *new* OS window
	 *  needs to hand off to that same thread's event loop — see the identical
	 *  reasoning in `open_archive_window` and `open_detail_window`.
	 */
	openAboutWindow: () => __TAURI_INVOKE<null>("open_about_window"),
	/**
	 *  Destroys the About popup — created on demand, not pooled, so the next
	 *  click just builds a fresh one.
	 * 
	 *  `async` for the same reason as `open_about_window`: tearing down an OS
	 *  window is thread-affine like creating one.
	 */
	closeAboutWindow: () => __TAURI_INVOKE<void>("close_about_window"),
	/**
	 *  Push a fresh snapshot of active downloads into the tray menu, called
	 *  roughly once a second from the frontend. Patches labels in place when the
	 *  same set of ids is still showing (by far the common case) so the menu
	 *  doesn't visibly flicker; otherwise rebuilds it.
	 */
	updateTrayDownloads: (items: TrayDownload[], tooltip: string) => __TAURI_INVOKE<null>("update_tray_downloads", { items, tooltip }),
	loadSettings: () => __TAURI_INVOKE<AppSettings>("load_settings"),
	saveSettings: (settings: AppSettings) => __TAURI_INVOKE<null>("save_settings", { settings }),
	getRunAtStartup: () => __TAURI_INVOKE<boolean>("get_run_at_startup"),
	setRunAtStartup: (enabled: boolean) => __TAURI_INVOKE<null>("set_run_at_startup", { enabled }),
	launchedAtStartup: () => __TAURI_INVOKE<boolean>("launched_at_startup"),
	loadPrefs: () => __TAURI_INVOKE<Prefs>("load_prefs"),
	saveAddDefaults: (args: SaveAddDefaultsArgs) => __TAURI_INVOKE<null>("save_add_defaults", { args }),
	setCategoryPath: (category: string, path: string) => __TAURI_INVOKE<null>("set_category_path", { category, path }),
	/**
	 *  Replaces prefs with an imported backup's. A backup never carries the proxy
	 *  password (export strips it), so an empty one keeps the current password.
	 */
	applyImportedPrefs: (prefs: Prefs) => __TAURI_INVOKE<null>("apply_imported_prefs", { prefs }),
	loadHistory: () => __TAURI_INVOKE<HistoryLoad_Serialize>("load_history"),
	saveHistory: (entries: HistoryEntry_Deserialize[]) => __TAURI_INVOKE<null>("save_history", { entries }),
	/**
	 *  Writes `csv` (built by the frontend, see `src/csvExport.ts`) to a path the
	 *  user picks in a native save dialog. Ok(None) = user canceled.
	 */
	exportHistoryCsv: (csv: string, defaultName: string) => __TAURI_INVOKE<string | null>("export_history_csv", { csv, defaultName }),
	exportBackup: (history: HistoryEntry_Deserialize[], defaultName: string) => __TAURI_INVOKE<string | null>("export_backup", { history, defaultName }),
	/**
	 *  Pick → parse → confirm. Applies nothing itself: the frontend applies
	 *  settings/history (it owns that state) and calls `apply_imported_prefs`.
	 *  Ok(None) = canceled at either step.
	 */
	importBackup: () => __TAURI_INVOKE<{
	exportedAt: number,
	settings: AppSettings,
	prefs: Prefs,
	history: HistoryEntry_Serialize[],
} | null>("import_backup"),
	runPowerAction: (action: string) => __TAURI_INVOKE<null>("run_power_action", { action }),
	/**
	 *  Swaps the registered shortcut. On failure the previous one is restored so
	 *  a typo never leaves the user with none. Persisting is the frontend's job
	 *  (via `save_settings`), only after this returns Ok.
	 */
	setGlobalHotkey: (accel: string) => __TAURI_INVOKE<null>("set_global_hotkey", { accel }),
	/**
	 *  Same preparation, minus the exit: the update installer takes the process
	 *  down itself moments later. Without this the installer would kill downloads
	 *  mid-flight and drop whatever history hadn't been debounce-saved yet.
	 *  The caller waits out the same grace period before installing.
	 */
	prepareForUpdate: () => __TAURI_INVOKE<void>("prepare_for_update"),
	grabberStatus: () => __TAURI_INVOKE<GrabberStatus>("grabber_status"),
};

/* Types */
export type AppSettings = {
	maxConcurrent?: number,
	globalLimitMbps?: number | null,
	minimizeToTray?: boolean,
	/**
	 *  "system" | "dark" | "light". Applied entirely on the frontend (see
	 *  `src/theme.ts`); Rust only persists it.
	 */
	theme?: string,
	notifications?: boolean,
	/**
	 *  User opt-in on top of the OS-level `prefers-reduced-motion` — only
	 *  ever adds reduction, never overrides the OS setting the other way.
	 *  Applied entirely on the frontend (see `src/reducedMotion.ts`); Rust
	 *  only persists it.
	 */
	reduceMotion?: boolean,
	/**
	 *  How many times a failed download retries itself automatically before
	 *  giving up for good, with backoff between attempts. 0 = disabled
	 *  (today's behavior). Applied entirely on the frontend (see
	 *  `useDownloads.ts`); Rust only persists it.
	 */
	maxRetryAttempts?: number,
	/**
	 *  Watch the clipboard for copied http(s) links and offer them as
	 *  downloads. Off by default: a watcher that reacts to every copy is
	 *  intrusive enough that it has to be opt-in. Applied entirely on the
	 *  frontend (see `useClipboardWatch.ts`); Rust only persists it.
	 */
	clipboardWatch?: boolean,
	/**
	 *  Hold the queue until `scheduled_start_time` each day, so downloads
	 *  added in the meantime wait instead of starting. Applied entirely on
	 *  the frontend (see `queueSchedule.ts`); Rust only persists it.
	 */
	scheduledStartEnabled?: boolean,
	/**  "HH:MM", 24-hour. Only meaningful when `scheduled_start_enabled`. */
	scheduledStartTime?: string,
	/**
	 *  Cap on rows kept in history.json. Unlike every other field here this
	 *  one IS read by Rust — `save_history` is the only writer, so it's the
	 *  backstop behind the frontend's own retention sweep.
	 */
	historyMaxEntries?: number,
	/**
	 *  Drop history rows finished more than this many days ago. 0 = keep
	 *  forever (the behavior before this setting existed). Applied on the
	 *  frontend, where the download list actually lives (see
	 *  `useHistoryPersistence.ts`).
	 */
	historyRetentionDays?: number,
	/**
	 *  Apply a downloaded update at startup instead of waiting for the user to
	 *  click through the restart prompt. On by default: a downloaded update
	 *  that nobody ever installs is the failure mode this exists to prevent,
	 *  and startup is the moment when restarting costs least. Only ever acts
	 *  when nothing is downloading. An update the feed marks `critical`
	 *  ignores this — that flag exists precisely for fixes that can't wait on
	 *  a preference. Applied entirely on the frontend (see
	 *  `useUpdateCheck.ts`); Rust only persists it.
	 */
	autoInstallUpdates?: boolean,
	/**
	 *  Sidebar shown as a full-width panel vs. a narrow icon rail. Applied
	 *  entirely on the frontend (see `src/components/Sidebar.tsx`); Rust
	 *  only persists it.
	 */
	sidebarCollapsed?: boolean,
	/**
	 *  System-wide shortcut that opens the Add window, in global-hotkey
	 *  syntax ("Ctrl+Alt+D"). "" = off (the default — a preset combo could
	 *  collide with another app). Registered by Rust (see `hotkey.rs`).
	 */
	globalHotkey?: string,
};

export type ArchiveEntry = {
	/**  Internal path, `/`-separated, no leading slash. */
	path: string,
	isDir: boolean,
	size: number,
	compressed: number | null,
	encrypted: boolean,
	/**  `"YYYY-MM-DD HH:MM"`, when the format records one. */
	modified: string | null,
};

export type ArchiveListing = {
	format: string,
	filename: string,
	total: number,
	entries: ArchiveEntry[],
	/**
	 *  A request/byte budget was hit before the whole directory was read —
	 *  `entries` is a partial (but not corrupt) listing.
	 */
	truncated: boolean,
	/**
	 *  The format encrypts its own file-name table (7z `-mhe`, RAR `-hp`),
	 *  so nothing could be listed at all; `entries` is empty.
	 */
	encryptedNames: boolean,
};

export type ArchiveRequest = {
	url: string,
	allowInsecure: boolean,
	headers: ([string, string])[],
	proxy: ProxyConfig | null,
};

export type BackupImport = BackupImport_Serialize | BackupImport_Deserialize;

export type BackupImport_Deserialize = {
	exportedAt: number,
	settings: AppSettings,
	prefs: Prefs,
	history: HistoryEntry_Deserialize[],
};

export type BackupImport_Serialize = {
	exportedAt: number,
	settings: AppSettings,
	prefs: Prefs,
	history: HistoryEntry_Serialize[],
};

export type ConnInfo = {
	downloaded: number,
	total: number,
	pieces: number,
};

export type DiskCheck = {
	enough: boolean,
	/**  Free bytes on the folder that's short; None when there's enough room. */
	free: number | null,
};

export type DownloadEvent = { event: "started"; data: {
	filename: string,
	path: string,
	total: number | null,
	connections: number,
	pieceSize: number,
	numPieces: number,
} } | { event: "progress"; data: {
	downloaded: number,
	total: number | null,
	speedBps: number | null,
	connections: ConnInfo[],
	/**
	 *  Fill level of each of `PIECE_BUCKETS` equal-sized slices of the
	 *  file, 0..=255. Fixed length regardless of file size, so a 100 GB
	 *  download costs no more per tick than a 10 MB one. Empty for a
	 *  single-connection download, which has no piece plan at all.
	 */
	pieces: number[],
} } | { event: "paused"; data: {
	downloaded: number,
} } | { event: "canceled"; data: {
	downloaded: number,
} } | { event: "verifying" } | { event: "finished"; data: {
	path: string,
	filename: string,
} } | { event: "error"; data: {
	message: string,
} };

export type GrabberStatus = {
	running: boolean,
	port: number | null,
};

/**
 *  One finished download. `state` always holds the real terminal state —
 *  "missing" is never stored, it is recomputed from disk on every load so a
 *  file that reappears recovers its original status.
 */
export type HistoryEntry = HistoryEntry_Serialize | HistoryEntry_Deserialize;

/**
 *  One finished download. `state` always holds the real terminal state —
 *  "missing" is never stored, it is recomputed from disk on every load so a
 *  file that reappears recovers its original status.
 */
export type HistoryEntry_Deserialize = {
	id?: string,
	url?: string,
	/**  Credential headers are stripped before this is written — see `needs_auth`. */
	headers?: ([string, string])[],
	allowInsecure?: boolean,
	checksum?: string,
	speedLimit?: number,
	filename?: string,
	filenameOverride?: string,
	path?: string,
	savePath?: string,
	total?: number | null,
	downloaded?: number,
	connections?: number,
	usedConnections?: number,
	state?: string,
	error?: string | null,
	/**
	 *  Kept so a redownload of a credential-gated link can reopen the page
	 *  that produced it and wait for the extension to capture a fresh request.
	 */
	referer?: string,
	needsAuth?: boolean,
	proxy?: ProxyConfig,
	finishedAt?: number,
	/**
	 *  When this download first entered the list; 0 for rows persisted before
	 *  this field existed (the frontend falls back to `finished_at` then).
	 */
	addedAt?: number,
};

/**
 *  One finished download. `state` always holds the real terminal state —
 *  "missing" is never stored, it is recomputed from disk on every load so a
 *  file that reappears recovers its original status.
 */
export type HistoryEntry_Serialize = {
	id: string,
	url: string,
	/**  Credential headers are stripped before this is written — see `needs_auth`. */
	headers: ([string, string])[],
	allowInsecure: boolean,
	checksum: string,
	speedLimit: number,
	filename: string,
	filenameOverride: string,
	path: string,
	savePath: string,
	total: number | null,
	downloaded: number,
	connections: number,
	usedConnections: number,
	state: string,
	error: string | null,
	/**
	 *  Kept so a redownload of a credential-gated link can reopen the page
	 *  that produced it and wait for the extension to capture a fresh request.
	 */
	referer: string,
	needsAuth: boolean,
	proxy: ProxyConfig,
	finishedAt: number,
	/**
	 *  When this download first entered the list; 0 for rows persisted before
	 *  this field existed (the frontend falls back to `finished_at` then).
	 */
	addedAt: number,
	missing: boolean,
};

export type HistoryLoad = HistoryLoad_Serialize | HistoryLoad_Deserialize;

export type HistoryLoad_Deserialize = {
	entries: HistoryEntry_Deserialize[],
	/**
	 *  False only when an existing file could not be parsed. The frontend uses
	 *  this to refuse to save for the rest of the session, so one bad byte
	 *  can't cascade into overwriting everything that was still readable.
	 */
	readable: boolean,
};

export type HistoryLoad_Serialize = {
	entries: HistoryEntry_Serialize[],
	/**
	 *  False only when an existing file could not be parsed. The frontend uses
	 *  this to refuse to save for the rest of the session, so one bad byte
	 *  can't cascade into overwriting everything that was still readable.
	 */
	readable: boolean,
};

export type Prefs = {
	/**  Add-window defaults, remembered across sessions. */
	connections?: number,
	speedLimitMbps?: number | null,
	/**
	 *  category id ("video" | "audio" | …) → absolute folder override.
	 *  Absent or empty = the built-in `<base>/<Category>` folder.
	 */
	categoryPaths?: { [key in string]: string },
	proxy?: ProxyConfig,
};

export type ProbeInfo = {
	total: number | null,
	supportsRanges: boolean,
	filename: string,
};

export type ProxyConfig = {
	enabled?: boolean,
	/**  "http" | "https" | "socks5h" */
	scheme?: string,
	host?: string,
	port?: number,
	username?: string,
	password?: string,
};

export type ResumableInfo = {
	path: string,
	url: string,
	filename: string,
	total: number,
	connections: number,
	downloaded: number,
	savePath: string | null,
	addedAt: number | null,
};

/**
 *  `save_add_defaults`'s own arguments, bundled into one struct so
 *  `connections` (a bare `usize`) can carry the `#[specta(type = Number)]`
 *  override needed to export it as `number` rather than `bigint` — that
 *  attribute is only available on `#[derive(Type)]` struct fields, not on
 *  raw `#[specta::specta]` command parameters. See `StartDownloadArgs` in
 *  `commands.rs` for the same pattern.
 */
export type SaveAddDefaultsArgs = {
	connections: number,
	speedLimitMbps: number | null,
	proxy: ProxyConfig,
};

/**
 *  A bare `u64`/`usize` command parameter can't carry the
 *  `#[specta(type = Number)]` override needed to export it as `number`
 *  rather than `bigint` — that attribute only works on `#[derive(Type)]`
 *  struct fields (see `StartDownloadArgs` above). Shared by the two
 *  speed-limit commands below, both of which take just this one value.
 */
export type SpeedLimitArgs = {
	bytesPerSec: number,
};

/**
 *  `start_download`'s own arguments, bundled into one struct rather than left
 *  as separate parameters: specta's `#[specta::specta]` macro (used to
 *  generate `../src/bindings.ts`) only implements its `SpectaFn` trait for
 *  functions of up to 10 parameters, and this command's domain arguments
 *  alone numbered 12. Grouping them costs nothing at the call site — Tauri's
 *  `invoke()` already sends named args as a single JSON object either way.
 */
export type StartDownloadArgs = {
	id: string,
	url: string,
	allowInsecure: boolean,
	headers: ([string, string])[],
	connections: number,
	resume: boolean,
	resumePath: string | null,
	expectedChecksum: string | null,
	speedLimit: number | null,
	filename: string | null,
	savePath: string | null,
	proxy: ProxyConfig | null,
};

export type TrayDownload = {
	id: string,
	label: string,
};

