// Pieces shared byte-for-byte between extension/ (Chrome) and
// extension-firefox/ (Firefox) — see each folder's background.js for the
// browser-specific logic (service worker vs event page, tabs.create vs
// launcher.html, static vs runtime-requested host permissions) that can't be
// shared. This file is a classic script, not a module: it's loaded via
// importScripts (Chrome service worker) or background.scripts (Firefox event
// page), neither of which supports ES imports, so everything hangs off
// globalThis.ADM instead.
//
// This is the source of truth. Copies under extension/common.js and
// extension-firefox/common.js are generated by scripts/sync-extension.mjs
// (`bun run sync:ext`) and checked for staleness by src/extensionSync.test.ts.

globalThis.ADM = {
  MENU_ID: "adm-download",
  ARM_MENU_ID: "adm-arm-capture",
  ARMED_KEY: "captureArmed",

  // Some hosts gate their direct download URLs behind a cookie the browser
  // sends automatically (ambient auth on <img>/<a> requests) but a plain HTTP
  // client has no way to obtain — ADM's Rust downloader is exactly that kind
  // of plain client. For a short allow-list of known hosts, look that cookie
  // up and forward it as a real `Cookie` header.
  COOKIE_FORWARD_DOMAINS: {
    "gofile.io": ["accountToken"],
  },

  matchForwardDomain(targetUrl) {
    let host;
    try {
      host = new URL(targetUrl).hostname;
    } catch {
      return undefined;
    }
    return Object.keys(ADM.COOKIE_FORWARD_DOMAINS).find(
      (d) => host === d || host.endsWith(`.${d}`),
    );
  },

  buildAdmUrl(url, referrer, cookie) {
    const params = new URLSearchParams({ url });
    if (referrer) params.set("referrer", referrer);
    if (cookie) params.set("cookie", cookie);
    return `adm://add?${params.toString()}`;
  },

  DOWNLOAD_LINK_RE: /^https?:\/\//i,
  CANT_GRAB_TITLE: "Can't grab this link",
  CANT_GRAB_MESSAGE:
    "This link has no real download URL (it's a JavaScript- or form-driven button, not a plain link). Right-click the page and choose \"Arm ADM capture\", then click the download button instead.",
};
